//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazUsuario.Lenguas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InterfazUsuario.Lenguas.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Eventos.
        /// </summary>
        internal static string btnCreateEvents {
            get {
                return ResourceManager.GetString("btnCreateEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Post.
        /// </summary>
        internal static string btnCreatePost {
            get {
                return ResourceManager.GetString("btnCreatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupos.
        /// </summary>
        internal static string btnGroups {
            get {
                return ResourceManager.GetString("btnGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensajes.
        /// </summary>
        internal static string btnMessages {
            get {
                return ResourceManager.GetString("btnMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Musica.
        /// </summary>
        internal static string btnMusic {
            get {
                return ResourceManager.GetString("btnMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string btnNext {
            get {
                return ResourceManager.GetString("btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotos.
        /// </summary>
        internal static string btnPhotos {
            get {
                return ResourceManager.GetString("btnPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video.
        /// </summary>
        internal static string btnVideo {
            get {
                return ResourceManager.GetString("btnVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escritura.
        /// </summary>
        internal static string btnWriting {
            get {
                return ResourceManager.GetString("btnWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguidores.
        /// </summary>
        internal static string Follower {
            get {
                return ResourceManager.GetString("Follower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguidos.
        /// </summary>
        internal static string InARow {
            get {
                return ResourceManager.GetString("InARow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a informacion.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para compartir y ver arte juntos.
        /// </summary>
        internal static string lblSubTituloRegistro {
            get {
                return ResourceManager.GetString("lblSubTituloRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrate.
        /// </summary>
        internal static string lblTituloRegister {
            get {
                return ResourceManager.GetString("lblTituloRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string linkLabel4 {
            get {
                return ResourceManager.GetString("linkLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        internal static string linkLabel5 {
            get {
                return ResourceManager.GetString("linkLabel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Tienes una Cuenta?.
        /// </summary>
        internal static string linklblRegitrarse {
            get {
                return ResourceManager.GetString("linklblRegitrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miembros.
        /// </summary>
        internal static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Grupo.
        /// </summary>
        internal static string NameGroup {
            get {
                return ResourceManager.GetString("NameGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apodo.
        /// </summary>
        internal static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foto de Perfil.
        /// </summary>
        internal static string profilePicture {
            get {
                return ResourceManager.GetString("profilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Publicidad.
        /// </summary>
        internal static string Publicity {
            get {
                return ResourceManager.GetString("Publicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Post.
        /// </summary>
        internal static string tituloCrearPost {
            get {
                return ResourceManager.GetString("tituloCrearPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Contrasenia.
        /// </summary>
        internal static string txtBoxConfirmPassword {
            get {
                return ResourceManager.GetString("txtBoxConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Nacimiento.
        /// </summary>
        internal static string txtBoxDateOfBirth {
            get {
                return ResourceManager.GetString("txtBoxDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string txtBoxMail {
            get {
                return ResourceManager.GetString("txtBoxMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Correo.
        /// </summary>
        internal static string txtBoxMailCode {
            get {
                return ResourceManager.GetString("txtBoxMailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string txtBoxName {
            get {
                return ResourceManager.GetString("txtBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apodo.
        /// </summary>
        internal static string txtBoxNickName {
            get {
                return ResourceManager.GetString("txtBoxNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrasenia.
        /// </summary>
        internal static string txtBoxPassword {
            get {
                return ResourceManager.GetString("txtBoxPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono.
        /// </summary>
        internal static string txtBoxPhone {
            get {
                return ResourceManager.GetString("txtBoxPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Telefonico.
        /// </summary>
        internal static string txtBoxPhoneCode {
            get {
                return ResourceManager.GetString("txtBoxPhoneCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string txtBoxSearch {
            get {
                return ResourceManager.GetString("txtBoxSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        internal static string txtBoxSurName {
            get {
                return ResourceManager.GetString("txtBoxSurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mundo.
        /// </summary>
        internal static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tus Musicas.
        /// </summary>
        internal static string YourMusic {
            get {
                return ResourceManager.GetString("YourMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tus Fotos.
        /// </summary>
        internal static string YourPhotos {
            get {
                return ResourceManager.GetString("YourPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tus Videos.
        /// </summary>
        internal static string YourVideos {
            get {
                return ResourceManager.GetString("YourVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tus Escrituras.
        /// </summary>
        internal static string YourWriting {
            get {
                return ResourceManager.GetString("YourWriting", resourceCulture);
            }
        }
    }
}
